version: "3"

services:
  mongodb:
    container_name: "docker_compose_local_social_media_hub_api_mongodb"
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  redis:
    container_name: "docker_compose_local_social_media_hub_api_redis"
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  localstack:
    container_name: "docker_compose_local_social_media_hub_api_localstack"
    image: localstack/localstack:latest
    restart: always
    ports:
      - "4566-4599:4566-4599"
      - "8055:8080"
    environment:
      - SERVICES=${SERVICES-s3,lambda,cloudformation,apigateway,dynamodb }
      - DEBUG=${DEBUG-true }
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-local }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - START_WEB=${START_WEB-1 }
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  mongodb-data:
  redis-data:
