version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update VARIANT to pick a node version: 10, 12, 14
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  mongodb:
    image: mongo:latest
    restart: always
    # volumes:
    #   - mongodb-data:/data/db
    # Runs MongoDB on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app
    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here
    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  redis:
    image: redis:latest
    restart: always
    # Runs MongoDB on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app
    # volumes:
    #   - redis-data:/data
  localstack:
    image: localstack/localstack:latest
    restart: always
    # ports:
    #   - "4566-4599:4566-4599"
    #   - "8055:8080"
    # Runs MongoDB on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app
    environment:
      - SERVICES=${SERVICES-s3,lambda,cloudformation,apigateway,dynamodb }
      - DEBUG=${DEBUG-true }
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-local }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      # - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

# volumes:
#   mongodb-data:
#   redis-data:
