#!/usr/bin/env sh
printf "starting docker stack\n"
sudo TMPDIR=/private$TMPDIR docker-compose --file=./docker/docker-compose.local.yml up -d
printf "started docker stack\n"

printf "sything aws-cdk stack\n"
sudo cdk synth > staging/SocialMediaHubAWSStack.template.yml
printf "synted aws-cdk stack\n"

printf "creating localstack stack\n"
sudo awslocal cloudformation create-stack --stack-name SocialMediaHubAWSStack --template-body file://./staging/SocialMediaHubAWSStack.template.yml
printf "created localstack stack\n"

printf "setting up mongo users\n"
mongo localDb <<EOF
db.createRole({
  role: "readWriteMinusDropRole",
  privileges: [
  {
    resource: { db: "localDb", collection: ""},
    actions: [ "collStats", "dbHash", "dbStats", "find", "killCursors", "listIndexes", "listCollections", "convertToCapped", "createCollection", "createIndex", "dropIndex", "insert", "remove", "renameCollectionSameDB", "update"]} ],
    roles: []
  }
);
use admin;
db.createUser({user: "localuser", pwd: "1234abcd", roles: [{role: "readWriteMinusDropRole", db: "localDb"}]})
quit()
EOF
printf "set up mongo users\n"

printf "starting localstack dynamodb admin ui\n"
DYNAMO_ENDPOINT=http://localhost:4569 dynamodb-admin
printf "started localstack dynamodb admin ui\n"