#!/usr/bin/env bash
printf "stopping local infra\n"
sudo awslocal cloudformation delete-stack --stack-name SocialMediaHubAWSStack
printf "deleted stack\n"
sudo docker-compose --file=./docker/docker-compose.local.yml down
printf "stopped local infra\n"