#!/usr/bin/env bash

printf "deleting localstack stack\n"
sudo awslocal cloudformation delete-stack --stack-name SocialMediaHubAWSStack
printf "deleted localstack stack\n"

printf "stopping docker stack\n"
sudo docker-compose --file=./docker/docker-compose.local.yml down
printf "stopped docker stack\n"