#!/usr/bin/env bash
printf "starting integration tests"
NODE_ENV=LOCAL node_modules/mocha/bin/_mocha --require ts-node/register -u bdd --timeout 999999 --colors --recursive --exit test/integration/data-management/user/**.ts
NODE_ENV=LOCAL node_modules/mocha/bin/_mocha --require ts-node/register -u bdd --timeout 999999 --colors --recursive --exit test/integration/data-management/user-token/**.ts
NODE_ENV=LOCAL node_modules/mocha/bin/_mocha --require ts-node/register -u bdd --timeout 999999 --colors --recursive --exit test/integration/data-management/twitter/**.ts
printf "finished e2e tests"
